name: Build & Release VGRING

on:
  push:
    tags:
      - 'v*'  # Ex: v1.0.1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Compile
        run: pio run

      - name: BIN Search
        id: get_bin
        run: |
          BIN_PATH=$(find .pio/build -name "*.bin" | head -n 1)
          echo "BIN=$BIN_PATH" >> $GITHUB_ENV
          echo "Found binary: $BIN_PATH"

      - name: Release cration
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.BIN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
